import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx,js,jsx}","./components/**/*.{ts,tsx,js,jsx}","./app/**/*.{ts,tsx,js,jsx}","./src/**/*.{ts,tsx,js,jsx}"],
  prefix: "",
  theme: {
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
    extend: {
      colors: {
        border: "hsl(var(--border))", input: "hsl(var(--input))", ring: "hsl(var(--ring))",
        background: "hsl(var(--background))", foreground: "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))", foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))", "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))", "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))", ring: "hsl(var(--sidebar-ring))",
        },
        nav: { active: "hsl(var(--nav-active))", "active-foreground": "hsl(var(--nav-active-foreground))" },
        surface: { DEFAULT: "hsl(var(--surface))", hover: "hsl(var(--surface-hover))" },
        success: { DEFAULT: "hsl(var(--success))", foreground: "hsl(var(--success-foreground))" },
        warning: { DEFAULT: "hsl(var(--warning))", foreground: "hsl(var(--warning-foreground))" },
      },
      borderRadius: {
        lg: "var(--radius)", md: "calc(var(--radius) - 4px)", sm: "calc(var(--radius) - 8px)",
        xl: "calc(var(--radius) + 4px)", "2xl": "calc(var(--radius) + 8px)", "3xl": "calc(var(--radius) + 16px)",
      },
      fontFamily: {
        sans: ["-apple-system","BlinkMacSystemFont","SF Pro Display","SF Pro Text","Segoe UI","Roboto","sans-serif"],
        mono: ["SF Mono","Monaco","Cascadia Code","Consolas","monospace"],
      },
      keyframes: {
        "accordion-down": { from:{height:"0"}, to:{height:"var(--radix-accordion-content-height)"} },
        "accordion-up":   { from:{height:"var(--radix-accordion-content-height)"}, to:{height:"0"} },
        "fade-up":        { from:{opacity:"0",transform:"translateY(16px)"}, to:{opacity:"1",transform:"translateY(0)"} },
        "fade-in":        { from:{opacity:"0"}, to:{opacity:"1"} },
        "scale-in":       { from:{opacity:"0",transform:"scale(0.94)"}, to:{opacity:"1",transform:"scale(1)"} },
        "slide-from-left":{ from:{opacity:"0",transform:"translateX(-16px)"}, to:{opacity:"1",transform:"translateX(0)"} },
        "float-up-down":  { "0%,100%":{transform:"translateY(0px)"},"50%":{transform:"translateY(-8px)"} },
        "float-slow":     { "0%,100%":{transform:"translateY(0) rotate(0deg)"},"33%":{transform:"translateY(-12px) rotate(1.5deg)"},"66%":{transform:"translateY(-5px) rotate(-1deg)"} },
        "progress-grow":  { from:{width:"0%"} },
        "wiggle":         { "0%,100%":{transform:"rotate(0deg)"},"20%":{transform:"rotate(-8deg)"},"60%":{transform:"rotate(8deg)"} },
        "tab-bounce":     { "0%,100%":{transform:"scale(1)"},"40%":{transform:"scale(1.25) translateY(-2px)"} },
        "ping-soft":      { "0%":{transform:"scale(1)",opacity:"1"},"75%,100%":{transform:"scale(1.8)",opacity:"0"} },
        "shimmer-sweep":  { from:{transform:"translateX(-100%)"}, to:{transform:"translateX(100%)"} },
      },
      animation: {
        "accordion-down":  "accordion-down 0.2s ease-out",
        "accordion-up":    "accordion-up 0.2s ease-out",
        "fade-up":         "fade-up 0.5s cubic-bezier(0.22,1,0.36,1) both",
        "fade-in":         "fade-in 0.4s ease both",
        "scale-in":        "scale-in 0.35s cubic-bezier(0.22,1,0.36,1) both",
        "slide-from-left": "slide-from-left 0.4s cubic-bezier(0.22,1,0.36,1) both",
        "float":           "float-up-down 3.5s ease-in-out infinite",
        "float-slow":      "float-slow 7s ease-in-out infinite",
        "progress":        "progress-grow 1.2s cubic-bezier(0.22,1,0.36,1) both",
        "wiggle":          "wiggle 0.4s ease-in-out",
        "tab-bounce":      "tab-bounce 0.3s cubic-bezier(0.34,1.56,0.64,1)",
        "ping-soft":       "ping-soft 1.5s ease-out infinite",
        "shimmer-sweep":   "shimmer-sweep 2s linear infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
